port=53
domain-needed
bogus-priv
no-resolv
server=8.8.8.8
server=8.8.4.4
strict-order
no-hosts
bind-interfaces
listen-address=5.175.245.8
listen-address=10.88.88.1
cache-size=150
address=/naxclow.com/5.175.245.8
address=/naxclow.com.cn/5.175.245.8
